default_agent: temperature_agent
agents:
  test_agent:
    name: test_agent
    entrypoint: /Users/bmurdock/git/temperature_alert/scripts/test_agentcore_runtime.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_12
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/bmurdock/git/temperature_alert
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: '717505361651'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: true
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: null
      memory_arn: null
      memory_name: test_agent_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  temperature_agent:
    name: temperature_agent
    entrypoint: /Users/bmurdock/git/temperature_alert/agent_runtime.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_12
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/bmurdock/git/temperature_alert
    aws:
      execution_role: arn:aws:iam::717505361651:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-598d64989e
      execution_role_auto_create: false
      account: '717505361651'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-717505361651-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: temperature_agent-CezOKQARRS
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:717505361651:runtime/temperature_agent-CezOKQARRS
      agent_session_id: 06cad843-7779-46c1-ad6f-97739c05d7c9
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: temperature_agent_mem-V62THM6YZC
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:717505361651:memory/temperature_agent_mem-V62THM6YZC
      memory_name: temperature_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_jGdk3Eacq/.well-known/openid-configuration
        allowedClients:
        - 21on1o485mre3ju22gohnvs21b
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
